site_name: rdbc-pgsql documentation - {{version}}
site_author: Krzysztof Pado
site_dir: target
strict: true
pages:
    - Introduction: index.md
theme: material

copyright: Copyright &copy; 2016 - 2017 Krzysztof Pado

extra:
  version: 1.0
  palette:
    primary: green
    accent: red
  social:
    - type: github
      link: https://github.com/rdbc-io
    - type: twitter
      link: https://twitter.com/rdbc_io

repo_name: rdbc-io/rdbc-pgsql
repo_url: https://github.com/rdbc-io/rdbc-pgsql
edit_uri: blob/master/rdbc-pgsql-doc/docs

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.toc(permalink=true)
  - pymdownx.inlinehilite

extra_css:
  - 'css/extra.css'
